#!/bin/bash
debug=""
if [ -z "$1" ] && [ "$1" == "debug" ]; then
    debug="debug"
fi

tests="$(ls tests/*.input)"
for t in $tests; do
    result="$(./master.py $debug < $t)"
    diff -s <(echo "$result") ${t%'.input'}'.output' &>/dev/null
    if [ $? == 0 ]; then
        echo "${t%'.input'} passed"
    else
        echo "${t%'.input'} failed"
        echo "$result"
    fi
done
